### ISSUE TITLE
Fasta file format

### ISSUE THREAD

**Issue by SumTot** [apallavicini/PLANiTS#1]
Hello!
I am interested in using your database, but for my analysis I would need that the fasta files are in the same format as the SILVA database:
•	_Fasta headers should have the format {IDENTIFIER}.{INTEGER}.{INTEGER} {TAXONOMY-STRING} where: 
o	IDENTIFIER is a unique sequence identifier which does not have spaces or periods
o	The difference between the two INTEGERs should be the length of the sequence, e.g. 1.1700 for a 1700 bp sequence
o	TAXONOMY-STRING is in SILVA or NCBI format, delimited by semicolons with no spaces (but spaces in taxon names allowed)
o	There is a single space before the TAXONOMY-STRING_

How can I get it? I think that the basic need is to include the "integers" but I don´t know how to do it.
I would appreciate any help!
Thanks a lot!

**Comment by claudioametrano** [comment]
> Hello!
> I am interested in using your database, but for my analysis I would need that the fasta files are in the same format as the SILVA database:
> • _Fasta headers should have the format {IDENTIFIER}.{INTEGER}.{INTEGER} {TAXONOMY-STRING} where: o IDENTIFIER is a unique sequence identifier which does not have spaces or periods o The difference between the two INTEGERs should be the length of the sequence, e.g. 1.1700 for a 1700 bp sequence o TAXONOMY-STRING is in SILVA or NCBI format, delimited by semicolons with no spaces (but spaces in taxon names allowed) o There is a single space before the TAXONOMY-STRING_
> 
> How can I get it? I think that the basic need is to include the "integers" but I don´t know how to do it.
> I would appreciate any help!
> Thanks a lot!

**Comment by claudioametrano** [comment]
Hi, are you trying to use our ITS database with a pipeline called phyloFlash, right? I can change the format for you.
Just few things look unclear from the description:
1)   1-1700 = 1699 so if the sequence length should be 1700 the right format would be 1.1701
2)   the taxonomy would be semicolon delimited (see below) is the format correct?... a space between sequence length and taxonomy and no semicolon at the end of the line
3)   which ITS reference database do you need (ITS1, ITS2, complete ITS)? 
Example:
**>MK676135.1.12 Chlorophyta;Ceae;Chlaales;Chlaceae;Ostrava;Ostrava meslinii
CACAGGATCATT**

**Comment by SumTot** [comment]
Hello,
Yes, that´s right. Thanks a lot! :)
1. At the beginning I though the same that you. But to be sure, I checked the format of SILVA database for some sequences and their information in the NCBI and it is not a real substraction. The INTEGERs refers to the first and the last nucleotides of the sequence. 
For ex., in a sequence of 1700 pb length, the INTEGERs will be: 1 and 1700. So, the right format is: 1.1700
2. It´s exactly like that, yes.
3. I would need the ITS2 database.

Your example is exactly how I would need it! :)
Thanks!

**Comment by claudioametrano** [comment]
Good, you can find my mail contact in my profile, email me so I can send you back the newly formatted ITS2 database, I won't upload it here as GitHub has limited space.

**Comment by SumTot** [comment]
:) Thanks!
