### ISSUE TITLE
Provide stable URLs to different database versions

### ISSUE THREAD

**Issue by milot-mirdita** [apallavicini/PLANiTS#2]
Would it be possible to upload PLANiTS to a location with stable URLs (e.g. Zenodo or GitHub Releases)?
Ideally the databases would also be available as separate files to minimize unnecessary downloads (split SiNTAX.fasta from fasta + taxonomy; split ITS1/ITS2/ITS).

**Comment by 54mu** [comment]
Hi, thank you for the great suggestion! Now you can find the compressed files as a release!
